name: flutter_pos_offline
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
